### ISSUE TITLE
No context menu when clicking in empty area of Grid

### ISSUE THREAD

**Issue by RaimundBarbeln** [tsuoanttila/GridExtensionPack#7]
When i click in the empty area at the bottom of a Grid, the context menu is not shown.
I need a context menu with the entry "new" there,  if there is no data in the Grid or the user clicks on the area below the last data row if the data does not fill the whole table area.

**Comment by tsuoanttila** [comment]
Hi,

This feature was recently included in the Vaadin core framework (starting from 7.6.0.alpha7) and this particular issue will be fixed in the next prerelease assuming my patch for https://dev.vaadin.com/ticket/19128 passes code review. I'll try to port a fix for the 7.5 based version of GridExtensionPack during the weekend as well, but since it actually needs some changes in the Grid code it might be a bit tricky...

**Comment by RaimundBarbeln** [comment]
I found out about 7.6.0.alpha7 after i wrote the issue. Unfortunately, we have a requirement to exchange all uses of the table component and use the grid instead, within the next two weeks.
I doubt that 7.6.0 will be stable until then.
We still have some other problems with context menu itself.
We will try the nightly build tomorrow to see if this solves at least some of the problems we have.

**Comment by tsuoanttila** [comment]
After a quick inspection it seems that I can't catch the event in the client-side due to a fault in the Grid widget. Hope you can take 7.6.0 to use, since I can't fix this.
